import { signIn, signOut, useSession } from 'next-auth/react'
import Head from 'next/head'

export default function Home() {
  const session = useSession()

  return (
    <>
      <Head>
        <title>BookWise</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Znk</h1>

        <div>
          <button onClick={() => signIn('google')}>Teste Login Google</button>
          <button onClick={() => signOut()}>Teste Logout</button>
        </div>

        <div>
          <button onClick={() => signIn('github')}>Teste Login Github</button>
          <button onClick={() => signOut()}>Teste Logout</button>
        </div>
        <p>{JSON.stringify(session)}</p>
      </div>
    </>
  )
}
